### ISSUE TITLE
Your connection is not secure

### ISSUE THREAD

**Issue by maniyax** [RHVoice/RHVoice.org#3]
The website tried to install an insufficiently protected connection.

rhvoice.org it uses a security technology that is outdated and vulnerable to attack. 

Error code: NS_ERROR_NET_INADEQUATE_SECURITY

**Comment by maniyax** [comment]
I do not know why such an error occurs in my Firefox.

It seems that there should be no problems with the certificate, because it is Cloudflare, but there is only a problem with this site.

**Comment by alex19EP** [comment]
I cannot replicate this in recent firefox and chromium. can you provide the exact version of your browsers?

**Comment by maniyax** [comment]
52.04, but it isn't normal situation for this version.

**Comment by alex19EP** [comment]
52.04 is out of support from Mozilla for a long time.
taking into account that firefox uses its own certificate store and not the system one, I don't think we can do anything about this.

especially since we do not influence the creation of the certificate at all.
